[tool.poetry]
name = "aula-06"
version = "0.1.0"
description = ""
authors = ["Bruno <bruno.eng.proj@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
